### ISSUE TITLE
Uncaught (in promise): Error: Push plugin not found! See logs.

### ISSUE THREAD

**Issue by hazeeb** [rajayogan/ionic2push-updated#2]
This is my app.component.ts , when i add  push.register(), it throws an error, given below the code. 
App was perfectly working before i add push.register() ,

Could you tell me, what I'm missing ?
```
import { Component } from '@angular/core';
import { Platform } from 'ionic-angular';
import { StatusBar, Splashscreen } from 'ionic-native';

import { HomePage } from '../pages/home/home';
import {
  Push,
  PushToken
} from '@ionic/cloud-angular';

@Component({
  template: `<ion-nav [root]="rootPage"></ion-nav>`
})
export class MyApp {
  rootPage = HomePage;

  constructor(platform: Platform, public push: Push) {
    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      StatusBar.styleDefault();
      Splashscreen.hide();
    });
    this.push.register().then((t: PushToken) => {
      return this.push.saveToken(t);
    }).then((t: PushToken) => {
      console.log('Token saved:', t.token);
    });
    this.push.rx.notification()
      .subscribe((msg) => {
        alert(msg.title + ': ' + msg.text);
      });
  }
}

```

Ionic Framework: 2.0.0-rc.3
Ionic Native: 2.2.3
Ionic App Scripts: 0.0.45
Angular Core: 2.1.1
Angular Compiler CLI: 2.1.1
Node: 6.9.1
OS Platform: Linux 4.8
Navigator Platform: Linux x86_64
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36

Error: Uncaught (in promise): Error: Push plugin not found! See logs.
    at s (http://localhost:8100/build/polyfills.js:3:8568)
    at s (http://localhost:8100/build/polyfills.js:3:8391)
    at http://localhost:8100/build/polyfills.js:3:8902
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:14051)
    at Object.onInvokeTask (/home/haseeb/designbids.com/ionicapp/node_modules/@angular/core/src/zone/ng_zone.js:229:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:13987)
    at e.runTask (http://localhost:8100/build/polyfills.js:3:11411)
    at i (http://localhost:8100/build/polyfills.js:3:8028)

**Comment by rajayogan** [comment]
Could you please check whether you have installed the push plugin. Also kindly run this app on a device / emulator. Cordova plugins won't work on browsers. Thanks.

**Comment by hazeeb** [comment]
Thank You, It run perfectly in device :)
